modLoader="javafml"
loaderVersion="[24,)"

issueTrackerURL="https://github.com/ochotonida/pumpkinlauncher/issues"
displayURL="https://minecraft.curseforge.com/projects/jack-o-launcher"
## logoFile=""
credits=""
authors="ochotonida"

[[mods]]
modId="jack_o_launcher"
version="1.13.2-1.0.0"
displayName="Jack-O'-Launcher"
updateJSONURL="https://raw.githubusercontent.com/ochotonida/pumpkinlauncher/1.13.2/update.json"
description='''Exploding jack-o'-lanterns and stuff'''

[[dependencies.jack_o_launcher]]
    modId="forge"
    mandatory=true
    versionRange="[24,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.jack_o_launcher]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.13.2]"
    ordering="NONE"
    side="BOTH"